config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "articles#index"

  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  paginates_per 15
  validates :title, presence: true, length: { minimum: 5 }
  has_many :comments, dependent: :destroy
  # belongs_to :user

  def self.ransackable_attributes(auth_object = nil)
    %w(title text)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, dependent: :destroy
  # has_many :articles, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  
  validates :first_name, presence: true
  validates :last_name, presence: true
  
  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :avatar])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show, :edit, :update, :destroy]
  def index
    @articles = Article.all.page params[:page]
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy

    redirect_to articles_path, notice: "Article was successfully destroyed."
  end

  private

    def find_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :text)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_article, only: [:create, :destroy]

  def create
    @comment = @article.comments.create(comment_params.merge(user_id: current_user.id))
    redirect_to article_path(@article)
  end

  def destroy
    @comment = @article.comments.find(params[:id])

    @comment.destroy
    redirect_to article_path(@article), notice: "Comment Destroyed Successfully"
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end

  def find_article
    @article = Article.find(params[:article_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>

  <% if @article.errors.any? %>
    <div id="error_explanation" class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-4">
      <h2 class="text-red-800">
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :title, class: "w-full bg-gray-200 text-gray-800 border border-gray-300 rounded py-2 px-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" %>
  </div>

  <div class="mb-3">
    <%= form.label :text, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_area :text, class: "w-full bg-gray-200 text-gray-800 border border-gray-300 rounded py-2 px-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" %>
  </div>

  <div class="mb-6">
    <%= form.submit "Save Article", class: "bg-purple-500 hover:bg-purple-700 text-white font-bold py-2 px-4 rounded shadow" %>
  </div>

<% end %>

app/views/articles/edit.html.erb
<div class="col-span-8 mx-auto w-[50%]">
  <h1 class="text-3xl font-bold text-center mb-8 shadow">Edit your Article</h1>
  
  <%= render 'form' %>

  <a href="<%= articles_path %>" class="block  flex justify-center items-start w-full   max-w-xs mx-auto bg-gray-500 hover:bg-gray-700 text-white font-bold rounded shadow-md text-center back_btn">Back</a>
</div>

app/views/articles/index.html.erb
<div class="flex flex-col w-full">
  <div class="flex justify-between items-center mb-4">
    <h1 class="text-2xl font-bold shadow">ARTICLES</h1>
    <%= link_to 'New article', new_article_path, class: "btn bg-purple-500 hover:bg-purple-700 text-white font-bold py-2 px-4 rounded shadow-lg" %>
  </div>

  <table class="w-full table-auto bg-white border border-gray-200 shadow-lg">
    <thead>
      <tr class="bg-gray-800 text-white">
        <th class="px-4 py-2 w-[25rem]">Title</th>
        <th class="px-4 py-2">Text</th>
        <th class="px-4 py-2" colspan="3">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @articles.each do |article| %>
        <tr class="border-t border-gray-200">
          <td class="px-4 py-2 text-center"><%= article.title %></td>
          <td class="px-4 py-2 text-center w-[40rem]"><%= article.text %></td>
          <td class="px-4 py-2 text-center flex justify-evenly">
         
          <%= link_to 'Destroy', article_path(article), data: { turbo_method: :delete, confirm: 'Are you sure?' }, method: :delete, class: "text-red-500 hover:underline ml-2" %>
          <%= link_to 'Show', article_path(article), class: "text-blue-500 hover:underline" %>
          <%= link_to 'Edit', edit_article_path(article), class: "text-blue-500 hover:underline ml-2" %>
        </td>
        
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="mt-4">
    <%= paginate @articles, class: "flex justify-center items-center" %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="col-span-8 mx-auto w-[50%]">
  <h1 class="text-3xl font-bold text-center mb-8 shadow">New Article</h1>
  
  <%= render 'form' %>

  <a href="<%= articles_path %>" class="block flex justify-center items-start w-full max-w-xs mx-auto bg-gray-500 hover:bg-gray-700 text-white font-bold rounded shadow-md text-center back_btn">Back</a>
</div>

app/views/articles/show.html.erb
<div class="col-span-8 mx-auto w-[50%]">
  <p class="text-xl font-bold">
    <strong>Title : </strong>
    <%= @article.title %>
  </p>

  <p class="text-xl font-bold">
    <strong>Text : </strong>
    <%= @article.text %>
  </p>

  <div class="flex justify-stretch mt-4">
    <%= link_to 'Edit', edit_article_path, class: "inline-block bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded shadow-md w-[175px] text-center" %>
    <%= link_to 'Back', articles_path, class: "inline-block bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded shadow-md ml-2 w-[175px] text-center" %>
  </div>

  <hr class="my-4">

  <h4 class="text-lg font-bold">Comments</h4>

  <%= render @article.comments %>

  <hr class="my-4">

  <h4 class="text-lg font-bold">Add a comment:</h4>

  <%= render 'comments/form' %>
</div>

app/views/comments/_comment.html.erb
<div class="border border-gray-200 p-4 rounded-lg mb-4">
  <p class="text-lg font-semibold">
    <strong>Commenter:</strong>
    <%= comment.user.full_name %>
  </p>
  <p class="text-base">
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

  <% if current_user && current_user == comment.user %>
    <div class="mt-4">
      <%= link_to 'Destroy Comment', [comment.article, comment], method: :delete, data: { confirm: 'Are you sure?' }, class: "inline-block bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded shadow-md" %>
    </div>
    <hr class="my-4 border-t border-gray-200">
  <% end %>
</div>

app/views/comments/_form.html.erb
<div class="col-span-3">
  <%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
    <!-- Uncomment the following lines if you want to display the commenter input field -->
    <!-- <div class="mb-4">
      <%= form.label :commenter, class: "block text-sm font-medium text-gray-700" %>
      <%= form.text_field :commenter, class: "block w-full mt-1 p-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
    </div> -->

    <div class="mb-4">
      <%= form.label :body, class: "block text-sm font-medium text-gray-700" %>
      <%= form.text_area :body, class: "block w-full mt-1 p-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
    </div>

    <div class="mt-4">
      <%= form.submit "Submit", class: "inline-block w-[200px] px-4 py-2 bg-blue-500 hover:bg-blue-700 text-white font-semibold rounded-md shadow-md transition duration-300 ease-in-out" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="bg-gray-100">
    <%= render "shared/navbar" %>
    <div class="container mx-auto mt-8">
      <div class="grid grid-cols-1 gap-4">
        <p class="text-green-600"><%= notice %></p>
        <p class="text-red-600"><%= alert %></p>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<% if current_user %>
  <nav class="bg-purple-600">
    <div class="container mx-auto px-4 py-2 flex justify-between items-center">
      <a href="/" class="text-white text-lg font-bold">Blog Application</a>
      <div class="flex items-center space-x-4">
        <span class="text-white"><%= current_user.full_name %></span>
        <span>
          <%= link_to 'Edit User', edit_user_registration_path, class: "inline-block bg-white text-purple-600 px-4 py-2 rounded-full shadow-md  hover:bg-purple-500 hover:text-white transition duration-300 ease-in-out" %>
        </span>
        <span>
          <%= link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete }, class: "inline-block bg-white text-purple-600 px-4 py-2 rounded-full shadow-md hover:bg-purple-500 hover:text-white transition duration-300 ease-in-out" %>
        </span>
      </div>
    </div>
  </nav>
<% else %>
  <nav class="bg-purple-600">
    <div class="container mx-auto px-4 py-2 flex justify-between items-center">
      <a href="/" class="text-white text-lg font-bold">Blog Application</a>
      <div class="flex items-center space-x-4">
        <div class="nav-item">
          <%= link_to 'Sign up', new_user_registration_path, class: "inline-block bg-white text-purple-600 px-4 py-2 rounded-full shadow-md hover:bg-green-500 hover:text-white transition duration-300 ease-in-out" %>
        </div>
      </div>
    </div>
  </nav>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<% unless controller_name == 'sessions' %>
  <p class="text-center mb-4">
    <%= link_to "Log in", new_session_path(resource_name), class: "text-blue-500 hover:underline" %>
  </p>
<% end %>

<% if devise_mapping.registerable? && controller_name != 'registrations' %>
  <p class="text-center mb-4">
    <%= link_to "Sign up", new_registration_path(resource_name), class: "text-blue-500" %>
  </p>
<% end %>

<% if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <p class="text-center mb-4">
    <%= link_to "Forgot your password?", new_password_path(resource_name), class: "text-blue-500" %>
  </p>
<% end %>

<% if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <p class="text-center mb-4">
    <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), class: "text-blue-500 hover:underline" %>
  </p>
<% end %>

<% if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <p class="text-center mb-4">
    <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name), class: "text-blue-500 hover:underline" %>
  </p>
<% end %>

<% if devise_mapping.omniauthable? %>
  <div class="text-center my-4">-------------- OR SIGN IN WITH --------------</div>
  <% resource_class.omniauth_providers.each do |provider| %>
    <p class="text-center mb-4">
      <%= link_to "Sign in with Google", omniauth_authorize_path(resource_name, provider), method: :post, class: "text-red-500 hover:underline" %>
    </p>
  <% end %>
<% end %>